variables:
  BuildConfiguration: Release
  
trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/*
stages:
  - stage: Build
    jobs:
    - job:
      displayName: Build and Publish
      steps:
      - task: GitVersion@5
        inputs:
          runtime: 'core'
          configFilePath: 'GitVersion.yml'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: 'src/**/*.csproj'
          packDirectory: '$(build.artifactStagingDirectory)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'GitVersion.SemVer'
          verbosityPack: 'Normal'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactStagingDirectory)'
          artifact: 'nuget'
          publishLocation: 'pipeline'
  - stage: Publish
    variables:
    - group: NugetFeed
    jobs:
    - deployment: DeployToNugetFeed
      displayName: Publish to nuget feed
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'Internal Nuget Feed'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: nuget
            - task: DotNetCoreCLI@2
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '$(TargetFeedId)'