variables:
  BuildConfiguration: Release
  
trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/*
stages:
  - stage: Build
    jobs:
    - job:
      displayName: Build and Publish
      steps:
      - task: GitVersion@5
        displayName: "Git Version"
        inputs:
          runtime: 'core'
          configFilePath: 'GitVersion.yml'

      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: 'src/**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: 'src/**/*.csproj'
          arguments: '-o $(build.artifactStagingDirectory)/out /p:Version=$(GitVersion.SemVer)'
          configuration: '$(BuildConfiguration)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'src'
          Contents: 'NuGet.config'
          TargetFolder: '$(build.artifactStagingDirectory)/final'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(build.artifactStagingDirectory)/out'
          Contents: '*.nupkg'
          TargetFolder: '$(build.artifactStagingDirectory)/final'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactStagingDirectory)/final'
          artifact: 'nuget'
          publishLocation: 'pipeline'
  - stage: PublishBetaFeed
    displayName: 'Publish to beta feed'
    variables:
    - group: BetaNugetFeed
    jobs:
    - deployment: DeployToBetaNugetFeed
      displayName: Publish to beta nuget feed
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'Beta Nuget Feed'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: nuget
            - task: DotNetCoreCLI@2
              displayName: "Push"
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '$(TargetFeedId)'


  - stage: PublishReleaseFeed
    displayName: 'Publish to release feed'
    variables:
    - group: ReleaseNugetFeed
    jobs:
    - deployment: DeployToReleaseNugetFeed
      displayName: Publish to beta nuget feed
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'Release Nuget Feed'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: nuget
            - task: DotNetCoreCLI@2
              displayName: "Push"
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
                selectOrConfig: 'config'
                nuGetFeedType: 'external'
                arguments: '--source github'
                publishFeedCredentials: '$(NugetFeed.ServiceConnection.Name)'
                nugetConfigPath: '$(Pipeline.Workspace)/nuget/NuGet.config'
