trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/*
stages:
  - stage: Build
    jobs:
    - job:
      displayName: Build and Publish
      steps:
      - task: GitVersion@5
        inputs:
          runtime: 'core'
          configFilePath: 'GitVersion.yml'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: 'src/Servitr.LogSink/*.csproj'
          packDirectory: '$(build.artifactStagingDirectory)'
          includesymbols: true
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'GitVersion.SemVer'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'nuget'
          publishLocation: 'pipeline'
  - stage: Publish
    variables:
    - group: NugetFeed
    jobs:

    - deployment: DeployToNugetFeed
      displayName: Publish to nuget feed
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'Internal Nuget Feed'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'nuget'
                targetPath: '$(Pipeline.Workspace)'
            - task: DotNetCoreCLI@2
              inputs:
                command: 'push'
                packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '$(TargetFeedId)'