variables:
  BuildConfiguration: Release
  
trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/*
stages:
  - stage: Build
    jobs:
    - job:
      displayName: Build and Publish
      steps:
      - task: GitVersion@5
        displayName: "Git Version"
        inputs:
          runtime: 'core'
          configFilePath: 'GitVersion.yml'
      - script: echo %Action%%BuildVersion%
        displayName: 'Set build version'
        env:
          Action: '##vso[build.updatebuildnumber]'
          BuildVersion: $(GitVersion.SemVer)
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: 'src/**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: 'src/**/*.csproj'
          arguments: '-o $(build.artifactStagingDirectory)/out'
          configuration: '$(buildConfiguration)'
          versioningScheme: byEnvVar
          versionEnvVar: 'GitVersion.SemVer'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(build.artifactStagingDirectory)/out'
          Contents: '*.nupkg'
          TargetFolder: '$(build.artifactStagingDirectory)/final'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactStagingDirectory)/final'
          artifact: 'nuget'
          publishLocation: 'pipeline'
  - stage: Publish
    variables:
    - group: NugetFeed
    jobs:
    - deployment: DeployToNugetFeed
      displayName: Publish to nuget feed
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'Internal Nuget Feed'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: nuget
            - task: DotNetCoreCLI@2
              displayName: "Push"
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '$(TargetFeedId)'